const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const START_GAME = 'START_GAME';
const SHOOT = 'SHOOT';
const UPDATE_PLAYER_MOVEMENT = 'UPDATE_PLAYER_MOVEMENT';
const LEAVE_ROOM = 'LEAVE_ROOM';
const HEART_PICKED_UP = 'HEART_PICKED_UP';

//EMITS
const GAME_STARTED = 'GAME_STARTED';
const SHOT = 'SHOT';
const WINNER = 'WINNER';
const UPDATE_ROOMS = 'UPDATE_ROOMS';
const ERASE_HEART = 'ERASE_HEART';

module.exports = {
  CREATE_ROOM,
  JOIN_ROOM,
  START_GAME,
  SHOOT,
  SHOT,
  GAME_STARTED,
  UPDATE_PLAYER_MOVEMENT,
  UPDATE_ROOMS,
  LEAVE_ROOM,
  WINNER,
  HEART_PICKED_UP,
  ERASE_HEART
};
