const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const START_GAME = 'START_GAME';
const SHOOT = 'SHOOT';
const IS_HIT = 'IS_HIT';
const UPDATE_PLAYER_MOVEMENT = 'UPDATE_PLAYER_MOVEMENT';

//EMITS
const GAME_STARTED = 'GAME_STARTED';
const SHOT = 'SHOT';
const NEW_ROOM = 'NEW_ROOM';

module.exports = {
  CREATE_ROOM,
  JOIN_ROOM,
  START_GAME,
  SHOOT,
  IS_HIT,
  SHOT,
  GAME_STARTED,
  UPDATE_PLAYER_MOVEMENT,
  NEW_ROOM
};
